### ISSUE TITLE
how to enforce buffer flush when user pick a specific quality to play

### ISSUE THREAD

**Issue by Awais-cb** [streamroot/videojs-hlsjs-plugin#51]
i am using this library for hls streaming but i does not flush the buffer when user picks specific quality any solution to that?

**Comment by ruslandinov** [comment]
Hello. 

In fact it should flush the buffer starting the next segment. This should happen because here https://github.com/streamroot/videojs5-hlsjs-source-handler/blob/master/lib/videojs5-hlsjs-source-handler.js#L57 we use this hls.js method for quality switching https://github.com/video-dev/hls.js/blob/master/doc/API.md#hlsnextlevel.

If you want a different hls.js quality switch method to be used, just change the https://github.com/streamroot/videojs5-hlsjs-source-handler/blob/master/lib/videojs5-hlsjs-source-handler.js#L57 accordingly.

**Comment by Awais-cb** [comment]
Thanks for you response sir.
this is the library i am using right now and i found no such method in it
http://5.254.96.179/cb_corporate/upload/player/CB_video_js/js/videojs5-hlsjs-source-handler.js
please have a look into it
