### ISSUE TITLE
The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

### ISSUE THREAD

**Issue by morkov4o** [streamroot/videojs-hlsjs-plugin#54]
Hi, 

we have the following issue on Windows XP SP2 / Chrome Version 49.0.2623.112

![23472428_1471299416319377_4330893360328460030_n](https://user-images.githubusercontent.com/900015/32852752-99e33774-ca41-11e7-84e2-d8b20c68e5ea.jpg)

We have 2 sources hls & mp4 .. 
without the m3u8 it works, but when hls source is added the error msg appear.

Any ideas?

**Comment by ruslandinov** [comment]
Hello. 
Not sure if it can work on Win XP, please try this test page http://streambox.fr/mse/hls.js-0.7.11/demo/?src=http%3A%2F%2Fwww.streambox.fr%2Fplaylists%2Fx212fsj%2Fx212fsj.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&dumpfMP4=false&levelCapping=-1&defaultAudioCodec=undefined in Windows XP SP2 / Chrome Version 49.0.2623.112. If it won't work, neither videojs5-hlsjs-source-handler will, due to lack of MediaSourceExtentions and/or codec support in  your system.
